name: Sync OneDrive CSVs

on:
  schedule:
    - cron: '*/1 * * * *'      # every minute
  workflow_dispatch:        # manual trigger in GitHub UI

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # use the GITHUB_TOKEN credential for pushing
          fetch-depth: 0            # fetch full history to allow proper commit

      - name: Fetch Schedule CSV from OneDrive
        run: |
          curl -L "https://onedrive.live.com/download?cid=CB13DF129A4A254C&resid=CB13DF129A4A254C%21seed0922bad0841f1ac4283202a612ad9&format=csv&sheet=Schedule" -o Schedule.csv

      - name: Fetch Adult CSV from OneDrive
        run: |
          curl -L "https://onedrive.live.com/download?cid=CB13DF129A4A254C&resid=CB13DF129A4A254C%21seed0922bad0841f1ac4283202a612ad9&format=csv&sheet=Adult" -o Adult.csv

      - name: Fetch Devo CSV from OneDrive
        run: |
          curl -L "https://onedrive.live.com/download?cid=CB13DF129A4A254C&resid=CB13DF129A4A254C%21seed0922bad0841f1ac4283202a612ad9&format=csv&sheet=Devo" -o Devo.csv

      - name: Fetch Rookie CSV from OneDrive
        run: |
          curl -L "https://onedrive.live.com/download?cid=CB13DF129A4A254C&resid=CB13DF129A4A254C%21seed0922bad0841f1ac4283202a612ad9&format=csv&sheet=Rookie" -o Rookie.csv

            - name: Fetch OneDrive Workbook (.xlsx)
        run: |
          curl -L "https://onedrive.live.com/download?cid=CB13DF129A4A254C&resid=CB13DF129A4A254C!seed0922bad0841f1ac4283202a612ad9" -o workbook.xlsx

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pandas openpyxl

      - name: Extract sheets to CSV
        run: |
          python - << 'EOF'
import pandas as pd
xls = pd.ExcelFile('workbook.xlsx')
sheets = ['Schedule','Adult','Devo','Rookie','Prep']
for sheet in sheets:
    df = pd.read_excel(xls, sheet_name=sheet)
    df.to_csv(f"{sheet}.csv", index=False)
EOF

      - name: Configure remote to use token
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/evdventures/D1_OneDrive.git

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Schedule.csv Adult.csv Devo.csv Rookie.csv Prep.csv
          git commit -m "Sync CSVs from OneDrive" || echo "No changes to commit"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
